### ISSUE TITLE
Bootstrap 4 alpha 6 not compatible

### ISSUE THREAD

**Issue by imhuytq** [DataTables/DataTablesSrc#100]
I'm using npm install datatables.net-bs4, but latest version not compatible with Bootstrap 4 alpha 6.
I look you have Bootstrap 4 alpha 6 integration: https://github.com/DataTables/Dist-DataTables-Bootstrap4/commit/c21aa93a4c8cc16e9f2ae1a9081690141751b268
Why do you not releases it?

**Comment by DataTables** [comment]
Simply because the next realise of DataTables isn't ready yet. The alpha 6 support will be included in that next release.
