### ISSUE TITLE
Remove CSS that isn't required - Bootstrap integration

### ISSUE THREAD

**Issue by DataTables** [DataTables/DataTablesSrc#105]
See @smasala's "side note" in #104.

What's the CSS doing there...

**Comment by Joyrex** [comment]
@DataTables Bootstrap 4 Beta 1 has finally come out, and with it some pretty extensive changes from Alpha 6. I think the item this Issue refers to has been resolved - see here: https://getbootstrap.com/docs/4.0/migration/#tables-1

**Comment by Joyrex** [comment]
I must say for the most part, going from Alpha 6 to Beta 1 doesn't seem to have broken anything DataTables-wise (that I've found so far).

Another DataTables-Bootstrap related item is the pagination: https://getbootstrap.com/docs/4.0/migration/#pagination

**Comment by DataTables** [comment]
Overall it looks like the DataTables / Bootstrap4 integration is holding. There have been a few changes required for Editor, but that will be in the next release of Editor (1.6.5). I'll be including Bootstrap 4 integration for DataTables in the download builder soon.
