### ISSUE TITLE
Documentation: Server-side PHP script code is missing

### ISSUE THREAD

**Issue by mpryvkin** [DataTables/DataTablesSrc#107]
Server-side PHP script is missing in [this example](https://datatables.net/examples/data_sources/server_side.html), although it's shown in [this example](https://datatables.net/examples/server_side/simple.html).

**Comment by DataTables** [comment]
Thanks for flagging this up. It was noted in the forum as well. I'll close then when I've had a chance to fix it.

**Comment by DataTables** [comment]
Fixed in aa849bd98f730afa8b1bd42f78759863e94c9d1a.
