### ISSUE TITLE
Dist-DataTables-Bootstrap not updated

### ISSUE THREAD

**Issue by bastuijnman** [DataTables/DataTablesSrc#108]
In the `1.10.15` tag of the repo there is correct support for Boostrap version `4-alpha6`, this is not reflected however in the corresponding published version (`1.10.15`) of Dist-DataTables-Bootstrap, in which for example the `page-link` class is not set on pagination links.

Is it possible to release a new version of the Dist-DataTables-Bootstrap package? Or will we need to wait until `1.10.16` is released?

Kind regards,

Bas Tuijnman
24i

**Comment by DataTables** [comment]
Bootstrap 4 integration is actually in [Dist-DataTables-Bootstrap4](https://github.com/DataTables/Dist-DataTables-Bootstrap4). The `Dist-DataTables-Bootstrap` repo will remain for Bootstrap3 support.

**Comment by bastuijnman** [comment]
Indeed, sorry I couldn't find the reference to that specific package and thus assumed there was only one.

Thanks a bunch for pointing me in the right direction 😄

**Comment by DataTables** [comment]
Since Bootstrap 4 is still in alpha, and things have already changed once during their alpha series, I haven't publicised that repo yet. When it goes beta I will do.
