### ISSUE TITLE
Inline styles injected by JavaScript blocked by Content-Security-Policy

### ISSUE THREAD

**Issue by bitplane** [DataTables/DataTablesSrc#112]
[As discussed](https://www.datatables.net/forums/discussion/comment/107953), a `Content-Security-Policy` that blocks injection by denying inline styles will cause the browser to block DataTables' `_fnApplyToChildren` function, which violates that policy.

To test, send a CSP header in your HTTP response with `object-src 'none'` as a policy, like so:

    Content-Security-Policy: default-src 'self' https:; object-src 'none'

Observe CSP reports in the JavaScript console.

**Comment by DataTables** [comment]
Thanks for posting this. Unfortunately, using a CSP to block inline styles would result in scrolling alignment being basically impossible since DataTables needs to be able to measure the column widths and then apply the widths to other columns. I don't see how that can be done without inline styles?

The only option I can see would be to not use scrolling in DataTables.

**Comment by bitplane** [comment]
I've done some testing and it looks like it's only a problem when it's inline styles in injected HTML. When they're set by DOM attributes it's fine.

To test, [datatables-inject-html-inline-styles-test.zip](https://github.com/DataTables/DataTablesSrc/files/1492354/datatables-inject-html-inline-styles-test.zip), run the webserver in Python and visit http://localhost:8000/ which will add an example CSP header onto every response.

 * The `injection-test` dir shows an example of the problem. Use F12 to view the console, then open the page.
 * The `datatables-test` shows the problem being logged to the console in the latest datatables (built from source today). 
 * The `datatables-fix-test` has code from my `remove-html-inline-css` branch, which I'll submit a pull request for in a moment.

The patch is just this:

```$ git show                                        
commit 034d987e1d5b7a5b200644e1c0d6130bc3a45600            
Author: Gaz Davidson <gaz@bitplane.net>                    
Date:   Tue Nov 21 17:26:23 2017 +0000                     

    Remove inline styles in injected HTML                  
                             
    fixes #112               

diff --git a/js/core/core.scrolling.js b/js/core/core.scrolling.js                                                     
index 5c13cf9..3abbd2b 100644                              
--- a/js/core/core.scrolling.js                            
+++ b/js/core/core.scrolling.js                            
@@ -340,14 +340,18 @@ function _fnScrollDraw ( settings )  
        // both match, but we want to hide it completely. We want to also fix their                                    
        // width to what they currently are                
        _fnApplyToChildren( function(nSizer, i) {          
-               nSizer.innerHTML = '<div class="dataTables_sizing" style="height:0;overflow:hidden;">'+headerContent[i]
+               nSizer.innerHTML = '<div class="dataTables_sizing">'+headerContent[i]+'</div>';                        
+               nSizer.style.height = "0";                 
+               nSizer.style.overflow = "hidden";          
                nSizer.style.width = headerWidths[i];      
        }, headerSrcEls );   
                             
        if ( footer )        
        {                    
                _fnApplyToChildren( function(nSizer, i) {  
-                       nSizer.innerHTML = '<div class="dataTables_sizing" style="height:0;overflow:hidden;">'+footerCo
+                       nSizer.innerHTML = '<div class="dataTables_sizing">'+footerContent[i]+'</div>';                
+                       Sizer.style.height = "0";          
+                       nSizer.style.overflow = "hidden";  
                        nSizer.style.width = footerWidths[i];                                                          
                }, footerSrcEls );                         
        }                    
```

**Comment by jjfeng520** [comment]
Hi @DataTables, I'm seeing a similar issue with **_fnCreateTr** in **jquery.dataTables.js**.

I get this error:
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://cdn.datatables.net/*"....
> 
> _fnCreateTr @ jquery.dataTables.js:3097

Is this a known issue/is there a fix for this?

**Comment by DataTables** [comment]
Can you update to 1.10.20 which is the current release. The version you are using was released before this bug was closed.

**Comment by jumpingjackson** [comment]
FixedColumns also runs into inline css CSP issues.   On 1.10.21

**Comment by rameshbsupekar** [comment]
![image](https://user-images.githubusercontent.com/14032094/92303385-e89b2700-ef91-11ea-8fe4-ca6b10d6f5cc.png)

above CSP issue exists in DataTables 1.10.20

is it possible to remove all inline css in datatables.js?
