### ISSUE TITLE
rows([ids], {search: 'removed'}) optimization

### ISSUE THREAD

**Issue by dagadbm** [DataTables/DataTablesSrc#118]
Hello,

I am working on a project that has a lot of data in the datatables and there is a use case that I need to know which rows were removed. I decided , at first, to use the rows([mySelectedIds], {search: 'removed'}) filter but alas I had to do use search: 'filter' instead and remove the duplicates myself.

Why? Because datatables removed is O(n^m) since they do 2 chained fors.

I propose to convert the masterData array into a map and then just iterate the filteredData (this way you get O(n) instead. 

Please let me know what you think.

--- Off topic ---
I have never done a PR request and I have no idea how so I am not sure I am the best person to fix this but I just wanted to let you guys know about this possible alternative :)

I wouldn't mind learning how to do a PR but it seems I need to fork this repo always? Is this common practice among other project? Can someone give me some link to get started on understanding how open source contributions work?

Thanks again :)

David.

**Comment by DataTables** [comment]
Hi David,

Thanks for opening this discussion - performance improvements are always welcome!

When selecting the rows that can be selected from, its [just a single `for` loop at the moment](https://github.com/DataTables/DataTablesSrc/blob/9df2759744d7d8fd50caac67b45b29545cc91fc6/js/api/api.selectors.js#L125) unless I'm missing something (highly likely!)?

For pull requests - yes, the process is that you fork the repo, make whatever changes you need, and then send a pull request so I can merge the changes in. [This page](http://www.firsttimersonly.com/) (and the links in it) contain information that might be of some interest.

**Comment by dagadbm** [comment]
[I am talking about this line](https://github.com/DataTables/DataTablesSrc/blob/9df2759744d7d8fd50caac67b45b29545cc91fc6/js/api/api.selectors.js#L120-L121)  (which was the use case I had to use). 

Will read that links as well :) thanks!

**Comment by DataTables** [comment]
Got it! $.inArray should be fast in a relatively modern browser since its a native call that jQuery makes (`Array.prototype.indexOf`). However, its still a for loop, just native in the Javascript engine, so it could be improved. An `if` condition there with a map conversion could I think make it O(2n), since you'd need an initial loop to do the conversion.

Certainly would be interested to see what you cook up there, and if you can provide a test case showing before / after, that would be fantastic.

**Comment by dagadbm** [comment]
I will see what I can do. Depends on my time as well. If I need some help should I use this issue or do you have some different form of communication?

**Comment by DataTables** [comment]
Here is good.

The first thing I would suggest is creating a little test page that demonstrates the issue and use the browser's profiler to get a CPU trace showing that the inArray is indeed causing an issue. That can then be used as a comparison for the fix.

**Comment by dagadbm** [comment]
I am testing this on my local computer with production data of the company I work with. In this particular case we have 51042 objects in the rows() call (its a crazy table I know)
```
        console.log('perf: ', performance.now() - p);
        var p = performance.now();
        var trash = datatableObject.rows(selectedRowsId, {search: 'removed'}).indexes();
        console.log('orig: ', performance.now() - p);
        console.log('orig value: ', trash.length);
        var p = performance.now();
        var trash2 = datatableObject.rows(selectedRowsId, {search: 'removed2'}).indexes();
        console.log('my: ', performance.now() - p);
        console.log('my value: ', trash2.length);
```

console.log:
```
orig:  1332.70000000266
orig value:  3
my:  16.200000001845183
my value:  3
```

This is my temporary code:

```
		else if ( order == 'current' || order == 'applied' ) {
		  if ( search == 'none' ) {
		    a = displayMaster.slice();
		  } else if ( search == 'applied' ) {
        a = displayFiltered.slice();
		  } else if ( search == 'removed' ) {
				a = $.map( displayMaster, function (el, i) {
				  return $.inArray( el, displayFiltered ) === -1 ? el : null;
				} );
		  }
		  else if ( search == 'removed2') {
	  		var filteredMap = {};
				$.each( displayFiltered, function (i, el) { filteredMap[el] = null; });
        a = $.map( displayMaster, function (el) {
           return filteredMap.hasOwnProperty(el) ? null : el;
        } );
		  }
		}
```

I also saw that the values from removed and removed2 are the same.

Quick question before I do a fork and try to make a PR out of this:
Do you have any cleaner way for me create the map?
Should I use hasOwnProperty ? (regarding browser compatibility etc)
Should I create a map form the  filteredData or from the master data? I created from the filterData so that the algorithm would be more or less the same. Is this ok for you?
Hope this is clear. I'm sorry I can't really be more specific on the test case for you because this is not my code.

Let me know what else I can do before I create the PR :)

**Comment by DataTables** [comment]
That looks good to me. Thanks for the performance details as well! Using the filtered map as you have looks correct.

I'd be tempted to try a simple `for` loop rather than `$.each` to create the map. Its perhaps not as neat, but it should be more performant since there is no context switching involved.

Using `hasOwnProperty` - yes there as well. I'm sort of tempted to say just do a check to see if `filteredMap[ el ] === undefined`, but I'm not sure it would improve performance, compatibility or readability, so `hasOwnProperty` should do nicely. I think it is supported in all browsers DataTables core currently supports.

Thanks for your input on this - this is why I love OSS :).

**Comment by dagadbm** [comment]
my first PR :)

ok I will fork the code and do the change (will also do the simple for)

**Comment by dagadbm** [comment]
so how can I link the PR with this issue?

**Comment by DataTables** [comment]
GitHub does it using some dark art magic :-). Going to close this in favour of your PR to address this issue.
