### ISSUE TITLE
[Bootstrap 4] .container-fluid added to table reduces table width

### ISSUE THREAD

**Issue by mrlife** [DataTables/DataTablesSrc#121]
The following `<div>` is being automatically wrapped around any table that's using DataTables. This seems like a bug. I can't think of any functional or aesthetic reason why a `.container-fluid` would be required to be wrapped around the table, reducing its width compared to other tables.

Is there a way to fix this or disable the behavior?

```
<div id="reports_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
```

**Comment by DataTables** [comment]
Agreed. It looks like it wouldn't even need a `container` class. Would you concur?

**Comment by mrlife** [comment]
I totally agree. Any Bootstrap containers should be the responsibility of the developer. Thanks for taking a look.

**Comment by mrlife** [comment]
That is awesome, thank you. Do you have any idea when the next release will be?

**Comment by DataTables** [comment]
Likely sometime this month. I'm not yet certain when though.

**Comment by mrlife** [comment]
Sounds great, just checking in on an updated release timeframe, if you have one.

**Comment by DataTables** [comment]
Sorry, yes. I've fallen behind with a few things. Its coming soon!

**Comment by DataTables** [comment]
I hope so! I'm a bit in a tangle with releases at the moment and need to sort stuff out, but yes I should really try to prioritise this.
