### ISSUE TITLE
slow tooltips on macOS High Sierra on Chrome/Safari/Firefox

### ISSUE THREAD

**Issue by ThePhoenixBird** [DataTables/DataTablesSrc#126]
Steps to reproduce:
1. Create a dataTable with buttons and each button has a **titleAttr** property to enable a tooltip on hover.
2. Browse this datable using latest Chrome or Safari on macOS High Sierra
3. Tooltip takes 2000-3000 ms to show up

Expected behavior:
Tooltip takes 1000ms to show up on Firefox on Linux/Windows

**Comment by DataTables** [comment]
The tooltips shown by the `title` attribute are something that is under control of the browser. DataTables doesn't attempt to show any tooltips. This would be something to [report back to Apple](https://www.apple.com/feedback/safari.html).
