### ISSUE TITLE
Data attribute for language sub-properties

### ISSUE THREAD

**Issue by jerone** [DataTables/DataTablesSrc#136]
Right now you can use the `language` [property](https://datatables.net/manual/i18n) to change the texts. And you can use the `language` data-attribute to change the text. But you can't mix both! 

I would like to override the `language` properties with some custom text for a specific table, using the data-attribute.

For example, I have the following default script:
```js
$('.example').DataTable( {
    language: {
      "sSearch": "Search in the data:",
      "sEmptyTable": "No results",
    }
} );
```
_Notice the use of the class in the selector `.example`. I use that because I want to use above snippet for every table._

Now, **one** table needs an custom `sEmptyTable` message. I tried to do the following:
```html
<table class="example" data-language='{"sEmptyTable": "Nothing here!"}'>
  <tr><td>data...</td></tr>
</table>
```

Aldo the data-attribute takes preference over the property (which is great), it does not account for sub-properties, and just override the whole `language` setting. Thus my custom `sSearch` message will be reset to the default.

What I **expected** to see, was still the use of my `sSearch` text.

I also tried the following, but as stated [here](https://datatables.net/forums/discussion/39981/setting-language-using-data-attributes-isnt-working) that is not supported:
```html
<table class="example" 
  data-language-sEmptyTable="Nothing here!"
  data-language--sEmptyTable="Nothing here!"
  data-language-s-empty-table="Nothing here!">
  <tr><td>data...</td></tr>
</table>
```

**Comment by DataTables** [comment]
Correct - it doesn't behaviour quite as expected at the moment. That's something I plan to address as part of the changes for 2.0.

**Comment by jerone** [comment]
Currently, I have solved it with the following code:

```html
<table class="example" 
  data-language--empty-table="Nothing here!">
  <tr><td>data...</td></tr>
</table>
```
```js
$('.example').each(function () {
	var datatable = $(this);
	var metadata = $.extend(true, {}, datatable.data());
	var metadataSettings = convertToNestedData(metadata);
	var datatableSettings = $.extend(true, datatableDefaults, metadataSettings);
	datatable.DataTable(datatableSettings);
});

// This will convert keys in JSON object with an dash to nested properties.
// Example: `convertToNestedData({"a-b":"value"});` ▶ `{"a":{"b":"value"}}`
// Partly altered from https://github.com/select2/select2/blob/c90adc102b5e9b2faea2b871b1c764416584ee07/dist/js/select2.full.js#L678-L710
function convertToNestedData(data) {
	for (var originalKey in data) {
		if (data.hasOwnProperty(originalKey)) {
			var keys = originalKey.split('-');

			var dataLevel = data;

			if (keys.length === 1) {
				continue;
			}

			for (var k = 0; k < keys.length; k++) {
				var key = keys[k];

				// Lowercase the first letter
				// By default, dash-separated becomes camelCase
				key = key.substring(0, 1).toLowerCase() + key.substring(1);

				if (!(key in dataLevel)) {
					dataLevel[key] = {};
				}

				if (k === keys.length - 1) {
					dataLevel[key] = data[originalKey];
				}

				dataLevel = dataLevel[key];
			}

			delete data[originalKey];
		}
	}

	return data;
}
```
