### ISSUE TITLE
First column orderable false displays incorrectly with Bootstrap 4.

### ISSUE THREAD

**Issue by bartdebever** [DataTables/DataTablesSrc#141]
When the first column is set to `orderable false`, the ordering arrow will display. Clicking on this column does nothing. When the table gets reordered using another column, the ordering arrow in the first column will dissappear.

**Comment by DataTables** [comment]
You need to also change the initial order using `order` since it will default to the first column. `columns.orderable` just controls the user's ability to change the ordering.

This and other support questions have been answered [on the forums](//datatables.net/forums).
