### ISSUE TITLE
Use of undeclared variable 'a' in api.cells.js 

### ISSUE THREAD

**Issue by nickrussler** [DataTables/DataTablesSrc#145]
In commit https://github.com/DataTables/DataTablesSrc/commit/042cb3bdaef7ae488dbc30c7ae24bb30d088a0a0 the declaration of the array `a` was moved into the iterator function, but it is referenced and used in the call to `this.cells` later (https://github.com/DataTables/DataTablesSrc/commit/042cb3bdaef7ae488dbc30c7ae24bb30d088a0a0#diff-bb3fdc4c5b312575dad117fc4bc696eeR147).

I might be missing something, but it seems to me as if that shouldn't work?

**Comment by DataTables** [comment]
Agreed! Something is going wrong there. Thanks for flagging this up - I'll take a look shortly.

**Comment by DataTables** [comment]
Poor variable naming got me in a fix there. Sorted now. Thanks again for flagging this one up!
