### ISSUE TITLE
pagination - disabled element should not be focusable

### ISSUE THREAD

**Issue by geopossachs** [DataTables/DataTablesSrc#146]
Hello,

we use your tool as a third party tool and love it 🥇 
one ours users send us a message and I would say he found a little bug

> we noticed that the previous/next button on the Datatable pagination were still focusable when they where disabled. It is usually common practice to prevent focus on disabled elements. The answer is to tabindex="-1" these elements.

I take a look and would say this is the class there to change it 
https://github.com/DataTables/DataTablesSrc/blob/master/js/ext/ext.paging.js

for people with a handicap is this might be a nice improvement

best regards

**Comment by DataTables** [comment]
Thanks for raising this - completely agree!
