### ISSUE TITLE
Search Bar Label and Input improperly generated: closing </label tag> in wrong place

### ISSUE THREAD

**Issue by ihelmer07** [DataTables/DataTablesSrc#149]
The Search Bar (upper right filter input) is improperly formatted - the <label></label> is encapsulating the entire input field.

Currently generated html (from example table on datatables.net):
`<div id="example_filter" class="dataTables_filter">`
   `<label>`
`      "Search:"`
`      <input type="search" class placeholder aria-controls="example">` 
`    </label>` **<- should be below "Search"**
`</div>`

**You can verify this on any default datatable - including the ones on [datatables.net](datatables.net)**
**Steps to recreate:**
1. go to any initialized datatable in any modern browser (chrome/firefox)
2. hover over the search field in the upper right of the table.
3. Right Click -> Inspect
4. Notice issue

**Impacted versions** - seems to be all
Screen Shot of datatables.net with incorrect </label> placement
![image](https://user-images.githubusercontent.com/14080785/66263591-44c25d80-e7bb-11e9-9e32-5e5b74ad40e6.png)

**Comment by DataTables** [comment]
Having the `input` element inside the `label` is perfectly valid HTML - see [the HTML specification](https://www.w3.org/TR/html52/sec-forms.html#the-label-element). It specifically says:

>The caption can be associated with a specific form control, known as the label element’s labeled control, either using the for attribute, or by putting the form control inside the label element itself.

**Comment by ihelmer07** [comment]
Apologies - I should have been more clear, I understand its valid HTML, however **Bootstrap 3 and Bootstrap 4** don't work as expected because of this design choice.

Because the input element is embedded in the label element, the input element does not expand to fit the column, or react responsively (expand/contract as the column div does). This leads to it being extra difficult/impossible to customize the default format via the [dom] (https://datatables.net/reference/option/dom) option because it isn't valid bootstrap.

If you were to not do this, bootstrap would work as expected instantly instead of requiring extra specific workarounds.

see the [bootstrap 4 docs](https://getbootstrap.com/docs/4.3/components/forms/#form-controls)

for example - the default bootstrap 4 dom string per your own docs is:
```
"<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
```

which would expect the "F" element - or search input field to be the full width of a col 6 or col 12 depending on breakpoint. That isn't happening due to the improper (to bootstrap) embedding of the input field into the label div.

Say I want to change the F location to be in the center (or <col-3l>< col-6f ><col- 3B>). The search input field again does not looks as expected by bootstrap.

**Comment by DataTables** [comment]
Thanks for your reply and the extra details. I've never really expected the input element to fill to the width of the column and I think it would look a little odd if it did in [this example](https://datatables.net/examples/styling/bootstrap4.html). The columns collapse down as expected and the input element is always useful there.

That said, this has come up before - I think its just that the explicit connection type is more common that the implicit that I am using, so I might change it for v2.

**Comment by ihelmer07** [comment]
I agree that it seems that explicit connection type is much more common than implicit and I would urge you to consider changing it for v2.

If you do - you'd still be able to match the current layout strictly by modifying default dom string's the column layout including column number (e.g. col-md-X) of the f  line.

for instance just by changing the default dom string - this _should_ look almost identical to current if you've changed to explicit: (notice the col-md-2 offset-md-4).


```javascript
"<'row'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-2 offset-md-4 'f>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
```

That's it - everything would still look extremely similar to normal BUT would retain the "standard" bootstrap functionality where the input box would be responsive and allow people do to customize the layout within that dom string without hacky css changes. Which is what spurred my issue.

 To give you perspective.

I'm trying to do this:
![image](https://user-images.githubusercontent.com/14080785/66574735-564c9200-eb3a-11e9-9e3b-5aa7e58a2a0d.png)

Which lead me to the following `dom` string:
```javascript
"<'row'<'col-sm-12 col-md-2 titleDiv'><'col-sm-12 col-md-8'f><'col-sm-12 col-md-2 addDiv'>>" +
"<'row'<'col-sm-12'tr>>" +
"<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>",
```

My assumption would be the 'f' would fill the columns per the usual bootstrap functionality BUT due to the above issue it doesn't.
it does this:
![image](https://user-images.githubusercontent.com/14080785/66574874-9f044b00-eb3a-11e9-978b-aed6dbc7f6e8.png)

which in order to get it to 'match' the standard bootstrap functionality I have to hack the css:

```css
#tableID div.dataTables_wrapper div.dataTables_filter label{
min-width:100%
}
#tableID div.dataTables_wrapper div.dataTables_filter input {
min-width:85%
}
```

and even then there could be responsive overlap issues at all view ports.

I hope this helps give some perspective! You'll be enabling more flexibility for formatting if you go to an explicit binding assumed by bootstrap!
