### ISSUE TITLE
DataTable table plugging not working jquery mysql

### ISSUE THREAD

**Issue by lakshitha1629** [DataTables/DataTablesSrc#150]
I add the table use in ajex and mysql..but dataTabe plugin not working..I can't modify of adding Search plugging and Pagination at the Script, in table tag, I add id 'dataTable' , in the script,
```

$(document).ready(function() {
$('#dataTable').DataTable();
});
```

**Comment by DataTables** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
