### ISSUE TITLE
Makes no sense how to join tables.

### ISSUE THREAD

**Issue by vkservicesllc** [DataTables/DataTablesSrc#161]
Sorry to bother. Could not find an answer on that one so decided to report as an issue.

I am combining information from 4 or 5 tables from mysql database using the relationship between primary and foreign keys. I could not figure out which method to use in such situation and whether it is supported on the server side using SSP class.

Thank you!

**Comment by DataTables** [comment]
Hi,

Per the template issue text, please post support questions in the DataTables forums:

> Please post support requests and questions in the DataTables forums at https://datatables.net/forums. Support requests posted here will be closed. The intention of this request is to allow all questions to be located in a single, searchable, location.
> 
> When you post your question in the DataTables forums, please ensure that you include a link to the page showing the issue so it can be debugged.

**Comment by DataTables** [comment]
For what it is worth - the demo SSP script does not support joins. There are a few discussions in the forum about this.
