### ISSUE TITLE
jQuery compliance (jQuery event shorthands are deprecated)

### ISSUE THREAD

**Issue by Mrks83** [DataTables/DataTablesSrc#162]
A few functions use jQuery event shorthands, marked as deprecated and removed in recent versions.
  
> jQuery.fn.blur() event shorthand is deprecated
> jQuery.fn.focus() event shorthand is deprecated

In order to be compliant with jQuery >= 3.3 these shorthands must be replaced.

How to reproduce: 
1. include `jquery-migrate.js`
2. do some actions (e.g. click dataTables buttons) 
3. check console output.

**Comment by DataTables** [comment]
Thanks - we'll get this sorted for the next patch.
