### ISSUE TITLE
Checkbox not in the center of the row

### ISSUE THREAD

**Issue by GerryGe** [DataTables/DataTablesSrc#164]
I am using the style of bootstrap 4.
I am not sure why set the checkbox margin-top: -6px in select.bootstrap4.css file.

Please see the screenshot:
![select bootstrap4](https://user-images.githubusercontent.com/6952917/82032525-ed2f8d00-96cd-11ea-8f49-936adc98b328.gif)

BTW, in datatables.net-select-bs4 package, there are js files which one is "select.bootstrap4.js". 
I want to know what this js does, because I found description of installation select extension and datatables.net-select-bs4 is styling via css only. Whether this is not need to include the select.bootstrap4.js in my project?
![image](https://user-images.githubusercontent.com/6952917/82034814-43ea9600-96d1-11ea-8d39-cc4e998cc097.png)

https://datatables.net/download/npm
```
npm install datatables.net-select
npm install datatables.net-select-bs4 // Styling via CSS only
```

**Comment by DataTables** [comment]
Yup - some prefer it to be at the top of the box, so it is consistent on multi-line rows. Something not quite right there still though. Could you link to a test case showing the issue please.

Also, in future, please could you post support requests in the forums? Thanks (it just means there is a central, searchable, corpus of knowledge for them).

**Comment by GerryGe** [comment]
Yes, thank you very much.

Do you want this?
http://live.datatables.net/godubilu/1/edit

I still want to know select.bootstrap4.js file does? Whether I need it?

**Comment by DataTables** [comment]
Thanks! Fixed here: https://github.com/DataTables/Select/commit/49e583841acab83c8e388381a09b1d5a50670491

**Comment by GerryGe** [comment]
Thanks.👍
