### ISSUE TITLE
jQuery.isArray is deprecated; use Array.isArray

### ISSUE THREAD

**Issue by bytestream** [DataTables/DataTablesSrc#171]
Quite a few `$.isArray` usages in the code that need switching to `Array.isArray`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

Not sure if the polyfill is needed, see above for browser compatibility.

**Comment by DataTables** [comment]
In DataTables 1.x yes, we'd need the polyfill. In v2 (which is in a branch and a wip), then no it wouldn't.

Thanks for this!

**Comment by bytestream** [comment]
Which file should I add the polyfill to? I sent a PR - https://github.com/DataTables/DataTablesSrc/pull/172

**Comment by DataTables** [comment]
Into core/core.internal.js please. I need to sort the code out for this sort of utility thing - but that will do for the moment :-)

**Comment by bytestream** [comment]
Updated the PR 👍
