### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by reviewher** [DataTables/DataTablesSrc#179]
GitHub thinks the license is in [license.txt](https://github.com/DataTables/DataTablesSrc/blob/master/license.txt).  It just says the source is MIT licensed.

If this repo and all of the code in it is MIT licensed, then putting the MIT license text in the file would get GitHub to figure out that this project is MIT.  For an example of this, check out [the sidebar in VueJS](https://github.com/vuejs/vue)

If it is not, then license.txt should be edited to reflect that.

**Comment by DataTables** [comment]
Thanks for pointing that out! Resolved now.

**Comment by reviewher** [comment]
40390ae66a9f5b54e3d453c0ea81cbf1ba9e0caa fixed the issue
