### ISSUE TITLE
Publish 1.10.23 to NuGet

### ISSUE THREAD

**Issue by JaredShaver** [DataTables/DataTablesSrc#185]
Please publish 1.10.23 to NuGet.

**Comment by DataTables** [comment]
Apologies - this should have been done automatically by the release scripts. I'll look into what has gone wrong and post back.

**Comment by DataTables** [comment]
Finally done: https://www.nuget.org/packages/datatables.net/1.10.23 .

Still working on the release scripts, but the latest files are there now at least :).
