### ISSUE TITLE
Support vanilla javascript along with jquery plugin

### ISSUE THREAD

**Issue by danny007in** [DataTables/DataTablesSrc#187]
like https://github.com/twbs/bootstrap 
in Bootstrap v5, not required of jquery plugin

**Comment by DataTables** [comment]
hi,

Please see [my comments in this thread in our forums](https://datatables.net/forums/discussion/51702#Comment_178528) for my thoughts on this. I'll write it up into a proper blog post sometime.

**Comment by DataTables** [comment]
Also [in the forum today](https://datatables.net/forums/discussion/67258/will-datatables-2-0-require-jquery#latest).
