### ISSUE TITLE
Wrong css class name

### ISSUE THREAD

**Issue by georgfranz** [DataTables/DataTablesSrc#194]
https://github.com/DataTables/DataTablesSrc/blob/b2245a55b4744be18d5eb175f27bbb195ff6a2cf/js/integration/dataTables.bulma.js#L42

Hi, 

bulma uses "is-half" not "is-one-half" for 50% columns

best,
Georg.

**Comment by AllanJard** [comment]
Hi Georg,

Many thanks! That's it fixed now. It will be in DataTables 1.11.3.
