### ISSUE TITLE
Bootstrap 5 table-striped corrupted by dataTables.bootstrap5.scss when rowGroup is used

### ISSUE THREAD

**Issue by programatix** [DataTables/DataTablesSrc#200]
I'm using the following,
```
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.5/r-2.2.9/rg-1.1.4/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.5/r-2.2.9/rg-1.1.4/datatables.min.js"></script>
```

When I enabled rowGroup, the table-striped is corrupted as such,
![image](https://user-images.githubusercontent.com/3293865/157422224-7f939ee8-1142-4639-926b-64fa2b851a8c.png)

I noted that all effected even rows has the following,
![image](https://user-images.githubusercontent.com/3293865/157421318-5848a7dc-8bda-4a89-9325-f7902ca654df.png)

I tried linking the css individually and if I removed dataTables.bootstrap5.css, then table-striped works fine even with rowGroup (both its css and js).

**Comment by AllanJard** [comment]
It [appears to work okay in this example](https://datatables.net/extensions/rowgroup/examples/styling/bootstrap5.html).

Perhaps you could open a support thread [in the forums](//datatables.net/forums) with a link to a test case showing the issue please?
