### ISSUE TITLE
After actualization sorting arrows are mismatched

### ISSUE THREAD

**Issue by LocalHeroPro** [DataTables/DataTablesSrc#206]
After
![image](https://user-images.githubusercontent.com/42643563/169257976-47f37dd4-6776-4070-b2a6-814a417ee816.png)

**Comment by AllanJard** [comment]
Are you using Bootstrap with `table-sm`? If so, [this commit from this morning](https://github.com/DataTables/DataTablesSrc/commit/c0b3288428a28fdd76d7521df40dbcc48952074a) will fix it. I'll be doing a 1.12.1 release with the fix shortly.

**Comment by LocalHeroPro** [comment]
Yes, you have right, I'm using `.table-sm`.
Waiting for fix and I'll write if it works.

**Comment by AllanJard** [comment]
Super thanks for letting me know.
