### ISSUE TITLE
Why pagination is showing pages if 0 recordsTotal is returned?

### ISSUE THREAD

**Issue by LocalHeroPro** [DataTables/DataTablesSrc#207]
![image](https://user-images.githubusercontent.com/42643563/171477401-aba927fd-1dc6-4130-864c-d7168bca6045.png)

**Comment by AllanJard** [comment]
Thanks for your question. However, per the "New issue" template text and the [Contributing document](/DataTables/DataTables/blob/master/Contributing.md), please post support requests in the [DataTables forums](//datatables.net/forums). Please also ensure that you link to a running test case showing the issue so it can be debugged. I'm sorry if the new issue text and contributing document wasn't clear enough on that topic.
