### ISSUE TITLE
Sorting breaks if column has data-order on only some rows

### ISSUE THREAD

**Issue by brunom** [DataTables/DataTablesSrc#217]
See http://live.datatables.net/tojuraqo/1/
I've made Tiger Nixon's age explicit for sorting. When you click on the age header, the order is random.

**Comment by AllanJard** [comment]
Yes, this is actually expected, If you use the data attributes, they need to be used on all rows for that column. DataTables doesn't look for one and then if it can't find it look for another source for it - it just always reads from the single source.
