### ISSUE TITLE
Option `responsive` missing from typings in v1.13

### ISSUE THREAD

**Issue by marekdedic** [DataTables/DataTablesSrc#228]
Hi, with the update to v1.13, more precisely with 87f5fd174b5724e3745e70b4478e1e3b1fbf05e4, the option `responsive` was removed from the typings. Is this intended? I don't see any mention of the option being removed, it just got removed from the typings.

See skaut/skautis-integration#392 for a demonstration of how this affects the usage :)

Thanks!

**Comment by AllanJard** [comment]
Yes - the `responsive` property is defined by the [Responsive extension](https://github.com/DataTables/Responsive/) (actual type definition is here](https://github.com/DataTables/Responsive/blob/master/types.d.ts#L22). It shouldn't have been in the core repo in the first place :).

You probably need to dump to Responsive 2.4.0 as well as DataTables core.

**Comment by marekdedic** [comment]
Ok, thanks for the explanation :)
