### ISSUE TITLE
Can we sponsor DataTables through github?

### ISSUE THREAD

**Issue by ppizarror** [DataTables/DataTablesSrc#233]
Hi! This issue is not related to any bug or feature request. I'm just asking If I can become a sponsor through github, like https://github.com/python. I would love to be able to donate even 1 dollar a month.

Greetings, =)

**Comment by AllanJard** [comment]
Thanks for asking! I've just submitted a request to Github to join the sponsors program. I'll update here when done (assuming they let me in ;)).

**Comment by AllanJard** [comment]
[Here we go](https://github.com/sponsors/AllanJard) :)
