### ISSUE TITLE
nullable parent in array notation

### ISSUE THREAD

**Issue by ryykrn** [DataTables/DataTablesSrc#237]
`columns: [
                { data: "x.y[,].z",
                defaultContent: "",
                },...`
in this setting when  x is null there is an error in this line
https://github.com/DataTables/DataTablesSrc/blob/8c95bddd1ebfe6453a70295ab537eb65df4faeef/js/api/api.util.js#L226
Because data variable used above without checking for null. But actually there is a null checking at the end of the for loop
https://github.com/DataTables/DataTablesSrc/blob/8c95bddd1ebfe6453a70295ab537eb65df4faeef/js/api/api.util.js#L257

So i think checking should also include
`data[ a[i] ] === null` condition. At least that is how i solved in my local.

**Comment by AllanJard** [comment]
Fixed now - thanks again!
