### ISSUE TITLE
Inconsistency in the documentation

### ISSUE THREAD

**Issue by pajusmar** [DataTables/DataTablesSrc#242]
I suspect there's an error on the following line as the  page is about vertical sizing of the table's viewport.

`<example title="Enable state saving"><![CDATA[`

https://github.com/DataTables/DataTablesSrc/blame/8026081f38443c76f07b9f3657c3cae80e8596a6/docs/option/scrollCollapse.xml#L14

**Comment by AllanJard** [comment]
Agreed. Thanks for flagging this up - [fix committed here](https://github.com/DataTables/DataTablesSrc/commit/3e83a73048537a299dd08867266ff371a5e1bcc1).
