### ISSUE TITLE
dt-control closed character not displayed well

### ISSUE THREAD

**Issue by nikomiranda** [DataTables/DataTablesSrc#244]
The new CSS introduced on 1.13.5 is not displayed well with bootstrap 5 and firefox (I didn't tested in other environments, sorry).

![image](https://github.com/DataTables/DataTablesSrc/assets/9426688/c77e167a-6ad8-46c5-bd03-3a6005413ef7)

content: "►";

I think it should be instead.

content: "▶"; (

Like the opened character is U+25BC (Black Down-Pointing Triangle), the closed character should be U+25B6 (Black Right-Pointing Triangle) instead of U+25BA (Black Right-Pointing Pointer)

**Comment by AllanJard** [comment]
Thank you - totally agree. That was a mistake using the pointing pointer :).

I've [committed the change](https://github.com/DataTables/DataTablesSrc/commit/e64f2a4be55b4c5b856df32b60f7cbbe1494caf8). Responsive had the same error [which is also now committed](https://github.com/DataTables/Responsive/commit/04d24bd6a3e8dce4fc10584d7b8eb30fec7ba88f).
