### ISSUE TITLE
ESM & JsDelivr: Restricting constraint to prevent matching the invalid 2.1.1 tag

### ISSUE THREAD

**Issue by weaverryan** [DataTables/DataTablesSrc#246]
Hi there!

I'm using JsDelivr's ESM for the `datatables.net-bs5` package - https://cdn.jsdelivr.net/npm/datatables.net-bs5@1.13.6/+esm

JsDelivr's ESM works great - but there's a problem in the code in this case:

```js
import e from"/npm/datatables.net@2.1.1/+esm";
```

That version - 2.1.1 - IS a tag in datatables.net, but it's invalid + marked as deprecated - https://www.npmjs.com/package/datatables.net/v/2.1.1. Because this (actually old) tag is used, the code crash with an ugly error. It makes sense, however, that this version is used: the `package.json` for `datatables.net-bs5` (and the other datatables integrations) is [>=1.13.4](https://github.com/DataTables/Dist-DataTables-Bootstrap5#L26). And so, it does kinda make sense that jsdelivr uses the 2.1.1 tag (even though we don't want it to!).

Would it be reasonable to restrict the version in the integrations to `^1.13.4`? That would match 1.13.4 and up, but NOT version 2.1.1. And if so, is that change made directly in [that repository](https://github.com/DataTables/Dist-DataTables-Bootstrap5) or is this data held in the central repository somewhere (I couldn't find it).

Thank you!

**Comment by tacman** [comment]
Version 2 is on the way?  Wahooo!  As you can imagine, I'd love to test it.  And to reiterate my plea that the examples in the documentation and on the website use vanilla javascript rather than jquery, since jquery is really only needed internally.

**Comment by tacman** [comment]
Until DataTables 2 comes out, would you consider changing this line to ^1.13.4, as Ryan suggested?  It's rare that the deprecated version is higher than the release version, so I'm not confident that jsdelivr is going to make that change.

https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/master/package.json#L26

Alternatively, can you remove 2.11 from npmjs, so it fixes this and doesn't interfere with the upcoming 2.0 release?

**Comment by AllanJard** [comment]
> Alternatively, can you remove 2.11 from npmjs

I asked npm to do that at the time. They said no :(.

Agreed - the dependency qualifier should be changed - I will make that change (likely next week - although not certain when I'll tag the release yet).

**Comment by weaverryan** [comment]
> Agreed - the dependency qualifier should be changed - I will make that change (likely next week - although not certain when I'll tag the release yet).

Thank you!!! We're moving Symfony to the JsDelivr+ESM approach, starting with a November release. This will help people not get tripped up ❤️

**Comment by tacman** [comment]
A gentle and respectful nudge for the dependency qualifier change... thanks.

**Comment by AllanJard** [comment]
Haven't forgotten - it is in my inbox along with a score of other things. I need to get a few others ticked off before I can make the next DataTaboes release. I hope to get it done fairly soon, but can't say for certain when that will be.

**Comment by AllanJard** [comment]
Could you try the 1.13.7 release of DataTables? The package file for the DataTables / Bootstrap 5 integration has an exact match on the [dependency for DataTables core now](https://github.com/DataTables/Dist-DataTables-Bootstrap5/blob/master/package.json).

The Scroller and KeyTable extensions were updated today and have changes in their compatibility tags (they actually are compatible with DataTables 2, so their `>=1.11` is correct, although might still cause issues with the old tag). Other extensions will update as releases for them happen.

**Comment by tacman** [comment]
Awesome, thanks!

I'm running into an issue with extensions, in that I don't know how to "connect" the plugins.

```javascript
import DataTables from "datatables.net-bs5";
import DataTablesSearchPanes from 'datatables.net-searchpanes-bs5';

let dt = new DataTable(el, {...});
dt.searchPanes(); // fail
```

I use a lot of plugins, pretty much all the bs5 ones, I'll start testing with all of them.  And yes, the version numbering has been confusing.

https://github.com/survos/SurvosApiGridBundle/blob/main/assets/package.json#L19-L26

```json
"importmap": {
      "datatables.net-bs5": "^1.13.6",
      "datatables.net-responsive": "^2.5.0",
      "datatables.net-searchpanes-bs5": "^2.2.0",
      "datatables.net-select-bs5": "^1.7.0"
}
```

**Comment by AllanJard** [comment]
There is no `searchPanes()` method on the API. There is a `searchPanes` namespace though - e.g. [`dt.searchPanes.container()`](https://datatables.net/reference/api/searchPanes.container()).

If that isn't working for you, please use [StackBlitz](https://stackblitz.com/) or similar to create a test case showing the issue.

**Comment by weaverryan** [comment]
That looks perfect - that “exact match” constraint for packages owned by the main package seems to be a common approach.

thank you!

**Comment by AllanJard** [comment]
Just for visibility, the jsdlivr issue whereby it would use deprecated versions has now been resolved as well.
