### ISSUE TITLE
GitHub and NPM's variants of 1.13.8's dist files still show 1.13.7 as their version number (with 1.13.8's changes)

### ISSUE THREAD

**Issue by EricDunsworth** [DataTables/DataTablesSrc#251]
Hi,

This probably isn't much of an issue in practice, but I figured it might still be worth reporting.

The variant of 1.13.8 that was released on [GitHub (DataTables/Dist-DataTables)](https://github.com/DataTables/Dist-DataTables) and [NPM](https://www.npmjs.com/package/datatables.net?activeTab=versions) still shows 1.13.7 in its JS files. But only the version number is outdated - all of 1.13.8's other changes are in place. By comparison, the CDN's variant of 1.13.8 shows the correct version.

Apart from being inconsistent with the CDN, the version number difference also causes GitHub and NPM's variants of 1.13.8 to falsely report ``DataTable.version`` as 1.13.7.

**Links:**
* DataTables CDN:
  * https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js (for reference)
  * https://cdn.datatables.net/1.13.8/js/jquery.dataTables.js (version correctly shows as 1.13.8)
* GitHub (``DataTables/Dist-DataTables``):
  * https://raw.githubusercontent.com/DataTables/Dist-DataTables/1.13.8/js/jquery.dataTables.js (shows 1.13.7 with 1.13.8's changes... diff it against the CDN's files to verify)
* NPM:
  * https://www.npmjs.com/package/datatables.net/v/1.13.8?activeTab=code (navigate to ``js/`` -> ``jquery.dataTables.js``... same as GitHub)

Thanks :)!

**Comment by AllanJard** [comment]
Should be sorted out with the 1.13.10 release (1.13.9 didn't hit npm due to an error in another package manager that meant I had to release 1.13.9 and 1.13.10).

**Comment by AllanJard** [comment]
Darn it - I thought I'd done that. Yes there should be. I'll sort that out :).

There is a small change in the CSS and two other tweaks, but basically its the same.

**Comment by EricDunsworth** [comment]
@AllanJard Oh whoops - guess my eyes were too glued to the JS files :P heh.

Thanks again :)!
