### ISSUE TITLE
Stripe option but no stripes

### ISSUE THREAD

**Issue by webbird** [DataTables/DataTablesSrc#253]
It seems that the stripe option is not working, even in the demos.

https://datatables.net/manual/styling/classes#stripe

Or am I missing something?

**Comment by AllanJard** [comment]
Looks okay to me. Perhaps your monitor just isn't showing the subtle shades of grey. Try looking at your monitor from an extreme vertical angle. That usually shows if there is a colour change that just isn't perceptible on a monitor normally.

**Comment by webbird** [comment]
Yes, you're right! That's *really* subtle! :D Thank you.
