### ISSUE TITLE
Ability to set database charset in ssp_class

### ISSUE THREAD

**Issue by emmanero90** [DataTables/DataTablesSrc#254]
In the function function sql_connect ( $sql_details ) under ssp_class,  the script will not work for non utf8 character.  I have to solve this by adding  charset=utf8mb4 to the $db  definition
"mysql:host={$sql_details['host']};dbname={$sql_details['db']};charset=utf8mb4"

**Comment by AllanJard** [comment]
In the SQL connection details array that is passed to `SSP::simple()` (second parameter) you can specify a character set [as shown here](https://github.com/DataTables/DataTablesSrc/blob/75b2d2c63a1e04f9c154c146ee1f8e391e45553d/examples/server_side/scripts/server_processing.php#L53C1-L59C3).
