### ISSUE TITLE
Scroller not working with Datatables v2

### ISSUE THREAD

**Issue by VeloAddict** [DataTables/DataTablesSrc#259]
Using:
```
"datatables.net": "^2.0.0",
"datatables.net-scroller": "^2.4.0",
```

```
    Uncaught TypeError: this.s.dt.oInstance.fnDraw is not a function (dataTables.scroller.mjs:271)
    at Scroller.measure (dataTables.scroller.mjs:271:1)
    at _Api.<anonymous> (dataTables.scroller.mjs:1337:1)
    at _Api.iterator (dataTables.mjs:6570:1)
    at _Api.<anonymous> (dataTables.scroller.mjs:1335:1)
    at Function.measure (dataTables.mjs:6690:1)
```

With Datatables 1.13.10 had no issues.

**Comment by AllanJard** [comment]
Thank you - looks like a missed a call to the legacy API. I'll patch it shortly.

**Comment by AllanJard** [comment]
[Fixed in the Scroller repo](https://github.com/DataTables/Scroller/commit/06f1a6e75d5cd43d8f7a6abc0b49b67a7ea1691e). It will be in Scroller 2.4.1 which I'll drop in the next few days.

**Comment by VeloAddict** [comment]
Any idea when will this fix be released?

**Comment by AllanJard** [comment]
Sorry - should be later today or tomorrow.
