### ISSUE TITLE
Wrong type DataTable.ext.classes 2.0.0

### ISSUE THREAD

**Issue by filipnestak** [DataTables/DataTablesSrc#265]
type `DataTable.ext.classes` not coresponding of real.
In 2.0.0 `DataTable.ext.classes` was refactored to new structure:

<img width="1632" alt="Snímka obrazovky 2024-03-15 o 16 04 43" src="https://github.com/DataTables/DataTablesSrc/assets/33693401/419518f0-a9a8-465e-80a1-3ae0ca73f519">

**Comment by AllanJard** [comment]
You are absolutely right. Thank you for flagging that up. I'll commit a fix shortly.

**Comment by AllanJard** [comment]
[Here we go](https://github.com/DataTables/DataTablesSrc/commit/666813ac95776a8d09e47528981ad9fbc7189292).

Thanks again for pointing this out. The fix will be in 2.0.3 which I'll probably drop next week.
