### ISSUE TITLE
ColReorder 2.0.0 release borked

### ISSUE THREAD

**Issue by Koopzington** [DataTables/DataTablesSrc#267]
https://github.com/DataTables/Dist-DataTables-ColReorder/blob/2.0.0/js/dataTables.colReorder.mjs#L12
So i was wondering why i had trouble using this extension in my vite project and after comparing the other extensions i came to the conclusion that the linked blurp shouldn't have landed in the .mjs file at all.
Aside from that the header in the file is claiming v1.7.0 (on the 2.0.0 tag) and master claiming v2.0.0-dev.
I decided to open an issue after trying to build the extension myself to confirm whether this was a bug or just an unfortunate accident and my resulting `built/DataTables/extensions/ColReorder/js/dataTables.colReorder.mjs` didn't have it.

**Comment by AllanJard** [comment]
You are absolutely right. Something has gone wrong with the distribution build there. The [CDN has the correct file](https://cdn.datatables.net/colreorder/2.0.0/js/dataTables.colReorder.mjs).

Thanks for flagging this up - I'll get this sorted out with a dot release - likely early next week.

**Comment by AllanJard** [comment]
Should be fixed now with the `datatables.net-colreorder` 2.0.1 release.
