### ISSUE TITLE
Layout option behaving differently than stated in documentation? (stacking vs. side by side)

### ISSUE THREAD

**Issue by Seltonu** [DataTables/DataTablesSrc#268]
Unsure if this is truly a bug / documentation error, but when using the `layout` property to set a custom top layout the items seem to **stack** rather than go side by side.

The [documentation](https://datatables.net/reference/option/layout#Values) for `layout` states the following for passing an array (emphasis mine)

> array - An array of any of the above options, providing the ability to **show multiple items next to each other**.

However when I try this, the behavior I get has elements stacking rather than side by side. I believe this to be an error, because per the [documentation](https://datatables.net/reference/option/layout#Values) stacking would be achieved by using `top2End`... `topNEnd`

I have created a simple JSFiddle to show the issue, where I believe we would expect the custom tool bar, pageLength, and search to all be on the same horizontal alignment rather than stacked.

https://jsfiddle.net/tf8nepLj/8/

![image](https://github.com/DataTables/DataTablesSrc/assets/10287568/b55a5c45-b426-47c5-be06-5eae1248cbcb)

**Comment by AllanJard** [comment]
Right, what the documentation means is that they are next to each other _in the DOM_. Apologies for the confusion - [you aren't the only one](https://datatables.net/forums/discussion/78715) to wonder about this.

I'm going to make a chance for DataTables 2.1 to have them actually display next to each other. Until then, a little CSS [as described here](https://datatables.net/forums/discussion/78230/layout-option-show-multiple-items-next-to-each-other) could be used to get the layout you are looking for.

I don't expect 2.1 to be too far away - perhaps a month or so.

**Comment by Seltonu** [comment]
@AllanJard confirming that this now behaves as expected in 2.1.4, thank you!
