### ISSUE TITLE
Wrong type of layout null

### ISSUE THREAD

**Issue by filipnestak** [DataTables/DataTablesSrc#271]
type of layout to remove parts of layout is wrong.
In doc: 
<img width="364" alt="obrázok" src="https://github.com/DataTables/DataTablesSrc/assets/33693401/24ec5586-b38e-4905-8c86-574f5e0fb26a">

<img width="754" alt="obrázok" src="https://github.com/DataTables/DataTablesSrc/assets/33693401/196e336a-e032-4050-bf4c-5ffdbeb8b9f7">

You should add explicit null of type Layout
<img width="871" alt="obrázok" src="https://github.com/DataTables/DataTablesSrc/assets/33693401/4c45a7b8-233d-4930-9810-76120242c571">

**Comment by AllanJard** [comment]
Good point - thanks for noting that. Fix committed :)

**Comment by filipnestak** [comment]
thank you, when will be release?
