### ISSUE TITLE
Processing indicator keep always visible

### ISSUE THREAD

**Issue by xJuvi** [DataTables/DataTablesSrc#278]
Today i tested the latest release v2.0.6 on my portal. I use a bootstrap 5.3 theme.

On some pages i use bootstrap tabs. Every tab has an own datatable via ajax (server-side). When i load the page, all datatables will be filled with data. But only the last (invisible) tab hide the processing indicator. All other tabs (also the first visible tab) will keep the message. The tables are working correctlly. I saw all data, there are no issue on browser console and all data loaded fully.

What should i do to hide the processing message? I think this is a bug. With dataTables v1.12.2 everything is working fine.

**Comment by AllanJard** [comment]
Please link to a test case is I can investigate.

**Comment by xJuvi** [comment]
Yeah of yourse.

https://live.datatables.net/cebimodi/1/edit

The example doesn't use real server side.... But when you scrol down in the first tab you can see the processing indicator. The second tab (same configuration) doesn't have it. Both tables are fully loaded. 
I linked the package i used:

https://datatables.net/download/#bs5/dt-2.0.6/fc-5.0.0/r-3.0.2/rg-1.5.0/rr-1.5.0/sc-2.4.2/sl-2.0.1

**Comment by AllanJard** [comment]
Thank you! Something wrong there for sure. I'll take a look into it tomorrow.

**Comment by AllanJard** [comment]
[This commit](https://github.com/DataTables/DataTablesSrc/commit/40bc402b50f69e37be92b0f22ced34e9ab095471) should fix it, and it is [in the nightly now](https://nightly.datatables.net/js/dataTables.js?2024-05-06a). Are you able to take it for a spin and say if that fixes it for you?

Allan

**Comment by xJuvi** [comment]
Well done. I think it is fixed with your commit.
Thanks!

**Comment by xJuvi** [comment]
Fixed with version 2.0.7.
Thanks!
