### ISSUE TITLE
data-visible="false" hides header but not data

### ISSUE THREAD

**Issue by chalda-pnuzig** [DataTables/DataTablesSrc#279]
In version 2, when utilizing `<th data-visible="false">` to hide a column, it appears that only the header element `<th>` is affected, leaving the data elements `<td>` visible. This behavior contrasts with the expected outcome observed in version 1.13.

Heres a link to a reproduction: 

- https://live.datatables.net/zonekeko/1/edit?html,output v.2 (not working)
- https://live.datatables.net/losavoji/1/edit?html,output v.1.13.11 (working)

**Comment by AllanJard** [comment]
I've [committed a change to DataTables](https://github.com/DataTables/DataTablesSrc/commit/d802465853307ad3dd4ccda577fb1f83a5a775a6) to address this (and other related issues.

I've put on the 2.1 branch as it is a bit too much internal reorganisation than I'm comfortable putting into a patch release. I'll be adding unit tests to make sure this doesn't happen again as well, as part of the 2.1 development work.

I'm not yet sure when 2.1 will drop - perhaps a few months. There are other things to work on for it as well.

Apologies for this error and the delay in getting a fixed release.
