### ISSUE TITLE
Responsive DataTable option only on first page (after 2.0.x upgrade)

### ISSUE THREAD

**Issue by xJuvi** [DataTables/DataTablesSrc#281]
I use the responsive option in my DataTables. Before i upgraded to version 2.0 everthing is working fine.

My setup:
DataTables 2.0.7
Server-Side processing
Bootstrap5 Theme

The first page is already correct rendered. The options which should be displayed in the child row are hidden and the icon to expand the child row is visible. When is use the option to show all results on one page, all results are corretly rendered. Only when i have multiple pages, the results are only applied the responsive option to the first page. All other pages doesn't have an expand icon, so i can't the the child rows.

An example is much difficult because the server-side processing can't be simulated in examples.

**Comment by AllanJard** [comment]
[This commit](https://github.com/DataTables/DataTablesSrc/commit/51b19797b71eb355e827d02e3be041ed9ec999b7) from yesterday should fix that. You could try the nightly version and see if that addresses it for you: https://nightly.datatables.net/js/dataTables.js?2024-05-10 .

**Comment by xJuvi** [comment]
Yes Thanks. #280 is the resoultion. I'll wait for the 2.0.8 release.

**Comment by xJuvi** [comment]
Fixed in version 2.8 ( commit 6abcccb )
