### ISSUE TITLE
Broken on Older (but recent) WebKit versions (iOS)

### ISSUE THREAD

**Issue by winrid** [DataTables/DataTablesSrc#282]
Hello! I launched a product using DataTables - it's really awesome, thank you. However, a few users came up to me and said the app does not work, the pattern was that they all had iphones.

It seems the issue is due to this regex in the code: `/(?<!\\):/g`

This uses a negative lookbehind which is not supported in many browser versions. It's starting to be pretty well supported now, but many people have phones that are a couple years old...

Right now I just added a build step that replaces this regex in the datatables source code with `/(^|[^\\]):/g`. Maybe this alternative regex would help.

**Comment by AllanJard** [comment]
I think you might be using DataTables 2.0.5? The error you note was resolved in 2.0.6 by [this commit](https://github.com/DataTables/DataTablesSrc/commit/c6dba9ff0cbeb2385799947218dba483d95f81c9). 2.0.7 is the current release of DataTables.

**Comment by winrid** [comment]
yay! Confirmed is fixed. Thanks for the quick reply.
