### ISSUE TITLE
Hiding columns breaks with ordering disabled in v2.1

### ISSUE THREAD

**Issue by joostdebruijn** [DataTables/DataTablesSrc#288]
I'm encountering the following console error with version 2.1.3: ```Cannot read properties of undefined (reading 'length') at m (dataTables.min.js:16:8975)```. It looks like this error has been introduced since version 2.1.0. The same code was running fine with v2.0.8.

It appears to be related when hiding columns with ordering disabled. See the following examples:

- https://live.datatables.net/gatoqeba/1/edit -> v2.1.3, with ordering **disabled** -> see the error in console
- https://live.datatables.net/vofabaxa/1/edit -> v2.1.3, with ordering **enabled** -> no error in console
- https://live.datatables.net/gaxujeba/1/edit -> v2.0.8, with ordering **disabled** -> no error in console

**Comment by dunkoh** [comment]
I can confirm this issue as well.

In our case we have some buttons that toggle hiding for different sets of columns.

**Comment by AllanJard** [comment]
Sorry about that! I've just [committed a fix and unit test](https://github.com/DataTables/DataTablesSrc/commit/8bbeef5d284dda6075031d11ad4dcd758893dd37) to make sure it doesn't happen again. Sorry I missed that one before.

The nightly build will carry the change shortly, and I'll do a 2.1.4 release with the change next week.
