### ISSUE TITLE
Setting DataTable.defaults.language when using searchPanes shows alert after version 2.1 

### ISSUE THREAD

**Issue by AkosLukacs** [DataTables/DataTablesSrc#290]
So this is kind of strange

Before v 2.1.0 I have used `DataTable.defaults.language = { url: 'i18n/hu.json' };` to set localization globally for my application. But after 2.1.0 it shows some rather strange errors:
```
DataTables warning: table id=DataTables_Table_0 
Requested unknown parameter 'total' for row 33, column 1. 
For more information about this error, please see https://datatables.net/tn/4
```

Reproduction: https://plnkr.co/edit/zFrVaJUDVpovLNuS?open=lib%2Fscript.js&preview
All good with 2.0.8. If I change DataTables 2.1.0 or later (index.html line 22), the alert is shown, and the search pane is broken.

Tested with other languages as well - in case Hungarian localization is missing something, but same behaviour with en-Gb or de-DE.

A workaround is setting the language in each DataTable like 
```js
var table = new DataTable('#example', {
   language: { url: '//cdn.datatables.net/plug-ins/2.1.3/i18n/hu.json' },
   // ...
});
```

(edit: sorry, accidentally hit ctrl-enter...)

**Comment by AllanJard** [comment]
[This commit](https://github.com/DataTables/SearchPanes/commit/e6e155da47787d4d021d0ee4176a5f36d78fd2b1) should have addressed this specific issue. Apologies I forgot to update this thread at the time. There is some [discussion about it](https://datatables.net/forums/discussion/comment/234237/#Comment_234237) in the forum as well.
