### ISSUE TITLE
toolbar option to hide/show columns w/ cookie support

### ISSUE THREAD

**Issue by goodale** [DataTables/DataTablesSrc#293]
While it is possible to programmatically hide or show a column, there doesn't appear to be a UI component that provides the end-user the option to select which columns should be visible.    I'm seeking a feature which provides this functionality.  Requirements are similar to the (ancient) ExtJS/Sencha data grid control from many years ago:

- Renders a drop-down widget at the rightmost edge of the header row.  
- Clicking the widget displays a list of all columns, with a checkbox beside each column
- Toggling the check boxes hides or shows the respective column
- Column visibility should 'honored' by the Export extension so that PDF, Excel and other exported files of the data only include the visible columns
- The user's selections should be 'sticky' via cookies so when the same table is rendered during a future session the column preferences are remembered.

This feature, once a standard component of ExtJS, seems to be missing from all of the various data table libraries.  It would be very advantageous of DataTables supported it, possibly via an extension.   End-users interacting with tables with a large number of columns would be able to more easily customize what they see and not have to export to Excel and then delete columns every time they export.

**Comment by AllanJard** [comment]
[Like this](https://datatables.net/extensions/buttons/examples/column_visibility/simple.html)? [More examples here](https://datatables.net/extensions/buttons/examples/column_visibility/index.html).

> Column visibility should 'honored' by the Export extension

Set the `columns` option for the export buttons to be `:visible`.

> The user's selections should be 'sticky' via cookies 

[Example here](https://datatables.net/extensions/buttons/examples/column_visibility/stateSave.html).

DataTables hasn't used cookies for state storing for many years. It uses localStorage by default, sessionStorage as an option. If you need a cookie, then use the state saving options of DataTables core to use cookies instead.
