### ISSUE TITLE
Pagination widget does not render page buttons correctly if table is initially hidden

### ISSUE THREAD

**Issue by xPaw** [DataTables/DataTablesSrc#295]
Repro: https://jsfiddle.net/90o3t51h/

```javascript
$("#example").DataTable({
  initComplete() {
    document.body.hidden = false
  }
})
```

I am initially hiding the table, and when the init is complete I show it, but for some reason it only shows one page button:

![image](https://github.com/user-attachments/assets/782d4e34-b4cd-44a2-b0c6-e8428dda212f)

Switching the page will update it and show all the other buttons:

![image](https://github.com/user-attachments/assets/f6ffc2ae-68cb-4ec0-82d4-0e0fd3b9bd57)

Seems to be a problem introduced in v2. This works fine in v1: https://jsfiddle.net/90o3t51h/1/

**Comment by AllanJard** [comment]
This is expected and is due to the responsive nature of the control. If an element is hidden it has no height / width and therefore the responsive calculations can't be made. You need to call the `draw()` method when your table is made visible.

https://jsfiddle.net/wxLj9q25/

**Comment by xPaw** [comment]
https://github.com/DataTables/DataTablesSrc/blob/643377800fbf3b1e050b8d59a843837710aea693/js/features/features.page.js#L155

Would it be reasonable to check `$(host).height() > 0` or `$(buttonEls[0]).outerHeight() > 0` here first? I am looking at the stack trace, it keeps trying to render buttons until it hits 1 and can't go lower any more.

**Comment by AllanJard** [comment]
Yup, I like that - thanks for the suggestion. [Committed here](https://github.com/DataTables/DataTablesSrc/commit/46bf228318d87acfc0d3d96d843129ebaac0cb86).

**Comment by xPaw** [comment]
that `buttonEls[0]` access should be after `buttonEls.length` check.

**Comment by AllanJard** [comment]
oh - damn. Thanks! [Fixed](https://github.com/DataTables/DataTablesSrc/commit/b075a834caf1d67b59d99a9e9c022c49079e9019).

Need to check why the unit tests didn't catch that...
