### ISSUE TITLE
Bug: `detectType` option does not seem to work

### ISSUE THREAD

**Issue by Teraskull** [DataTables/DataTablesSrc#299]
Hi!

The https://datatables.net/reference/option/detectType docs say this feature is since `2.1.6`, but while testing on `2.1.8`, I noticed that `detectType: false` does not disable type detection for my columns with dates. They still get formatted as dates (`dt-type-date` class gets added).

As a workaround, I have to set `type: "string"` on that column to disable type detection.

Is there something I'm missing, or not completely understanding how it's supposed to work? I also have `serverSide: true` set.

Thanks for your great work!

#

Also, a really small nit, don't want to create a separate issue for this, but in the https://datatables.net/manual/server-side#Sent-parameters docs, the `order` parameter only has `column` and `dir` documented:

![image](https://github.com/user-attachments/assets/ea4cd87b-52ed-403c-a1e2-369a7e954a08)
 
But the dataTable request also contains the `name`:

![image](https://github.com/user-attachments/assets/cc07afd6-2c80-41a2-8636-ab08b9fc5f9b)

**Comment by Teraskull** [comment]
Just saw your commit cf99b72 with the fix, consider this issue closed, thanks!

**Comment by AllanJard** [comment]
Good point about the order column name parameter. I've committed that in and it will be deployed soon :).

Thanks!
