### ISSUE TITLE
Tag for 1.10.5

### ISSUE THREAD

**Issue by EgoAleSum** [DataTables/DataTablesSrc#36]
The "compiled" repository DataTables contains the tag for 1.1.0.5, but I can't find it in the DataTablesSrc repository. Could you please add the correct tag?
Thanks

**Comment by DataTables** [comment]
Completely forgot to tag this repo. Thanks for letting me know about that error.

I've added it at the correct point now: https://github.com/DataTables/DataTablesSrc/releases/tag/1.10.5 .
