### ISSUE TITLE
Closure compiler install path issue.. 

### ISSUE THREAD

**Issue by michahell** [DataTables/DataTablesSrc#46]
running 
`running ./make.sh js` requires the closure compiler in the following dir on OSX (10.10.3):
`/usr/local/closure_compiler/compiler.jar` which is a nonexisting path if the closure compiler is installed by for example NPM: `/usr/local/lib/node_modules/google-closure-compiler/compiler.jar`
Of course it's madness to check all possible paths for the google closure compiler. What I did, was to add a symlink to where I have the closure compiler installed:

`mkdir /usr/local/closure_compiler`
`cd /usr/local/closure_compiler`
`ln -s compiler.jar /usr/local/lib/node_modules/google-closure-compiler/compiler.jar`

**Comment by DataTables** [comment]
Thanks for flagging this up. I really need to get around to documenting the build procedure and options for DataTables!

**Comment by michahell** [comment]
You're welcome! I think adding something to the documentation is just fine.
I found out that you can set the path on line 5:
```CLOSURE="/usr/local/closure_compiler/compiler.jar"``` in:
https://github.com/DataTables/DataTablesSrc/blob/master/build/include.sh
:)

**Comment by DataTables** [comment]
I completely forgot to update this issue when I published some build instructions for DataTables: https://datatables.net/manual/development/build .

The default is still the same closure compiler path as before - I'll probably update that for NPM in the not too distant future (more work on the build stuff needs to be done!).
