### ISSUE TITLE
Automatic selection of respective category

### ISSUE THREAD

**Issue by gauravmak** [DataTables/DataTablesSrc#52]
When user clicks on a link which leads any of the reference topics (Options, API, Events, etc.), The category of the link is not being selected automatically and user gets shown all the available options.

For example, *http://datatables.net/reference/option/#select* should automatically select all the options for **Select** extension. The same happening with API, Events, etc.

Thanks.

**Comment by DataTables** [comment]
Oops - thanks! Fixed on the site now :-)
