### ISSUE TITLE
NPM - Sass

### ISSUE THREAD

**Issue by artursopelnik** [DataTables/DataTablesSrc#77]
The package _"datatables.net-dt"_ include only css files. It is possible to add a "npm sass-version"?

**Link:**
https://datatables.net/download/npm#NPM-package-installation

**Comment by DataTables** [comment]
Thanks for the suggestion. It isn't something I am currently planning. If you want the SASS you can grab it from this repo.

**Comment by artursopelnik** [comment]
That we do currently for our project but they can't freeze release by a tag name. Only by commit hash...
`
npm install git+https://github.com/DataTables/DataTablesSrc.git // success
npm install git+https://github.com/DataTables/DataTablesSrc.git#a6b3a35b74eacafcb30a9fb6f51fbd85554385b3 // success
npm install git+https://github.com/DataTables/DataTablesSrc.git#1.10.12 // fails
npm install git+https://github.com/DataTables/DataTablesSrc.git#v1.10.12 // fails
`

**Comment by DataTables** [comment]
I've recently had to add a `package.json` file which calls this package `datatables.net-src` - I'll get that registered and published on NPM.

**Comment by DataTables** [comment]
[Published now](https://www.npmjs.com/package/datatables.net-src). You can grab the files directly from this repo now. We might move things around a little for the build process to help support the npm "way" a bit better, but the source files will likely stay as they are.
