### ISSUE TITLE
dataTables_empty class should also be available on TR

### ISSUE THREAD

**Issue by gsouf** [DataTables/DataTablesSrc#8]
When a table is empty there is the following tbody :

``` html
<tbody>
   <tr class="odd">
      <td valign="top" colspan="3" class="dataTables_empty">
         Aucune donnée disponible dans le tableau
      </td>
   </tr>
</tbody>
```

I think it would be reliable to also apply "dataTables_empty" class to the TR too.

**Comment by fds-github** [comment]
Since rows in my table are clickable, I'm trying to style them as follows:

````
tbody tr:not(.dataTables_empty) {
    cursor: pointer;
}
````

The problem of course is that the class is on the TD instead of the TR.  Having it on the TR (which seems more intuitive) would allow a pure CSS solution.
