### ISSUE TITLE
Browser support for Safari 10.0.2 is unclear for excelHtml5 button

### ISSUE THREAD

**Issue by tziporaziegler** [DataTables/DataTablesSrc#94]
I'm working with the excelHtml5 button:
https://datatables.net/reference/button/excelHtml5

According to the browser support documentation, Safari 10.0.1 and earlier are not supported:

> Safari: Yes (tech preview 18+) Safari 10.0.1 and earlier are _not_ supported.

The latest version of Safari is 10.0.2:
https://en.wikipedia.org/wiki/Safari_version_history

Is this version supported or not?

The code excludes all Safari, regardless of the version, with `!_isSafari()`:
```
    DataTable.ext.buttons.excelHtml5 = {
        className: 'buttons-excel buttons-html5',

        available: function () {
            return window.FileReader !== undefined
                && _jsZip() !== undefined
                && !_isSafari()
                && _serialiser;
        },

...
```

Either the documentation needs to be updated to say that Safari 10.0.2 and earlier is not supported, or the code needs to be updated to check the browser version to only exclude old versions of Safari with something like:

```
return window.FileReader !== undefined
    && _jsZip() !== undefined
    && (!_isSafari() || parseFloat(navigator.userAgent.match(/safari\/(\d(.+\d)?)/i)[1]) > 602.2)
    && _serialiser;
```

**Comment by DataTables** [comment]
Thank you. [Fixed here](https://github.com/DataTables/Buttons/commit/c8ae22d169aa6877b83871e71c7b5203f9d64b23). I don't know Apple's release plans of course, but I'm reasonably sure that it will be a 10.1 or 11 update to Safari before we see this the download support in a release version of Safari.
